Add PWA feature to stacker news
stackernews/stacker.news pull request #263
Opened 2023-05-05 06:40 UTC by spraveenitpro

Summary:

I am adding PWA feature to stacker news so that It can be installed on a phone/desktop like a native app.

Testing Instructions:

1. Once you have switched to this branch then open the site in a browser of a phone or on the desktop computer and you should get an option to install it as a PWA like this ![](https://d.pr/i/m62xik+)
2. If any issues, feel free to leave a comment.

2023-05-07 14:57 UTC, ekzyis requested changes
Lot of code style changes. Will take another view when these were undone.

2023-05-07 14:57 UTC, ekzyis commented on .env.sample
Why was this file deleted? This is file is required.

2023-05-07 14:57 UTC, ekzyis commented on next.config.js
> +    }
Please undo code style changes like this.

I assume it was just auto-formatting but changes like these make it hard to see what was actually changed and what the actually required changes are.

2023-05-07 14:57 UTC, ekzyis commented on next.config.js
> +}))
Didn't take a look at all these changes since I assume most are because of changed indentation.

Will take another look when this was undone

2023-05-07 14:57 UTC, ekzyis commented on public/manifest.json
> +    "description": "Your favourite news sources",
Maybe this should use the default SN description?

`It's like Hacker News, but we pay you Bitcoin`

2023-05-11 22:37 UTC, huumn commented
Thanks for the solid effort! I'll send some sats to your SN account.

I decided to go with `display: minimal-ui` until email login and navigation are figured out on all browsers.

For SN archeologists:
1. `next-pwa` fails to build SN into a service worker (at least in dev mode but probably in prod too ... which means it probably needs a lot more config to actually do anything)
2. email based magic link login is incompatible with `display: standalone` on iOS Safari
3. `standalone` strips back button navigation, which the average user will want, so we need a solution to that too

2023-05-11 22:37 UTC, closed without merging

2023-05-24 13:36 UTC, ekzyis commented
For reference: #263